# Uncomment this file to enable multilanguage site support

[en]
languageName = "English"
languagedirection = "ltr"
title = "1001"
weight = 1
[zh-cn]
languageName = "Chinese"
languagedirection = "ltr"
title = "一千零一夜"
weight = 2
favicon="favicon/favicon.ico"