# Uncomment this file to enable multilanguage site support

[en]
languageName = "English"
languagedirection = "ltr"
title = "Example Site"
weight = 1
[zh-cn]
languageName = "Chinese"
languagedirection = "ltr"
title = "Example Site"
weight = 2
